Schwabe:
  Theme:
    # Add google fonts
    addGoogleFonts: true
    apiKey: ''

    # Fonts which are available
    fontOptions: []

    # Theme settings
    #
    # The {packageKey} placeholder is replaced by the package key of the site the module works on.
    #
    scss:
      # Contains all scss rules and @imports to other files
      importPaths: 'resource://{packageKey}/Private/Styles/'
      mainScssFile: 'Main.scss'

      # Expanded, Nested (default), Compressed, Compact, Crunched
      formatter: 'Leafo\ScssPhp\Formatter\Nested'

      # Output path has to be in Package Public folder
      outputPath: 'resource://{packageKey}/Public/Styles/'
      outputFilename: 'Main.css'

      # Your scss variables which should be customizeable in the BE module
      # Add/remove to your needs
      # Valid types: textfield, color, font (See Settings.yaml.example or Readme.md of details)
      presetVariables: []

    # Optionally the settings can be placed below "sites", indexed by package key, if more flexibility is needed:
    #
    # sites:
    #   'Acme.AcmeCom':
    #     fontOptions: ...
    #     scss: ...
    #
    # The site-specific settings will be merged with the "scss" values, so those can be used to define common
    # default values.
    sites: []

Neos:
  Neos:
    modules:
      administration:
        submodules:
          theme:
            label: 'Theme Settings'
            controller: 'Schwabe\Theme\Controller\BackendController'
            description: 'Customize your Theme'
            icon: 'icon-sliders'
            privilegeTarget: 'Schwabe.Theme:BackendModule'
            additionalResources:
              styleSheets:
                - 'resource://Neos.Twitter.Bootstrap/Public/3.3/css/bootstrap.css'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/lib/codemirror.css'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/lint/lint.css'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/fold/foldgutter.css'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/hint/show-hint.css'
                - 'resource://Schwabe.Theme/Public/Components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.css'
                - 'resource://Schwabe.Theme/Public/Styles/Theme.css'
              javaScripts:
                - 'resource://Schwabe.Theme/Public/Components/codemirror/lib/codemirror.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/fold/foldcode.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/fold/foldgutter.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/fold/brace-fold.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/fold/comment-fold.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/fold/indent-fold.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/lint/lint.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/lint/css-lint.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/edit/trailingspace.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/edit/closebrackets.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/edit/matchbrackets.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/hint/show-hint.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/addon/hint/css-hint.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror-scss-linter/scsslint.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror-scss-linter/scss-lint.js'
                - 'resource://Schwabe.Theme/Public/Components/codemirror/mode/css/css.js'
                - 'resource://Schwabe.Theme/Public/Components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js'
                - 'resource://Schwabe.Theme/Public/JavaScript/fontSelector.js'
                - 'resource://Schwabe.Theme/Public/JavaScript/Main.js'
    userInterface:
      requireJsPathMapping:
        'Schwabe.Theme/Validation': 'resource://Schwabe.Theme/Public/JavaScript/Inspector/Validators'
      translation:
        autoInclude:
          'Schwabe.Theme': ['*']
    fusion:
      autoInclude:
        Schwabe.Theme: true
